[global]
         auth_client_required = cephx
         auth_cluster_required = cephx
         auth_service_required = cephx
         cluster_network = 172.16.20.198/24
         fsid = a8918a03-943d-49e9-a5ec-71f9215b9496
         mon_allow_pool_delete = true
         mon_host =  172.16.20.198
         osd_pool_default_min_size = 2
         osd_pool_default_size = 3
         public_network = 172.16.20.198/24

[client]
         keyring = /var/www/html/Config/Ceph/$cluster.$name.keyring

[mon.ceph]
         public_addr = 172.16.20.198