KafkaServer {
  org.apache.kafka.common.security.plain.PlainLoginModule required
  username="admin"
  password="Kafka_password123498"
  user_admin="Kafka_password123498"
  user_alice="Alice-secret2";
};
Client {
   org.apache.zookeeper.server.auth.DigestLoginModule required  
   username="kafka"
   password="Kafka_password123498";
};
KafkaClient {
   org.apache.zookeeper.server.auth.DigestLoginModule required
   username="admin"
   password="Kafka_password123498";
};
